/**
 * IRIS AI - Central Dispatcher & Scanner Orchestrator
 * Integrates the Python scanner service, Graph Engine, and Database Manager.
 */

class ScannerOrchestrator {
  constructor() {
    this.excelParser = new ExcelParser();
    this.docxParser = new DocxParser();
    this.pdfParser = new PdfParser();
    this.graphEngine = new GraphEngine();
    this.dbManager = new DatabaseManager();
  }

  /**
   * Determine file type from extension / mime
   */
  getFileCategory(file) {
    const name = file.name.toLowerCase();
    const type = file.type.toLowerCase();

    if (type.startsWith('image/') || /\.(png|jpg|jpeg|webp|gif|svg|bmp)$/i.test(name)) {
      return 'image';
    }
    if (type.includes('spreadsheet') || type.includes('excel') || type.includes('csv') || /\.(xlsx|xls|csv)$/i.test(name)) {
      return 'excel';
    }
    if (type.includes('word') || type.includes('document') || /\.(docx|doc)$/i.test(name)) {
      return 'docx';
    }
    if (type.includes('pdf') || /\.pdf$/i.test(name)) {
      return 'pdf';
    }
    return 'unknown';
  }

  /**
   * Scan single file and return aggregated draft report
   */
  async scanFile(file, onProgress = () => {}) {
    const category = this.getFileCategory(file);

    if (category === 'unknown') {
      throw new Error(`Unsupported file format: ${file.name}. Supported formats: Spreadsheets (.xlsx, .xls, .csv), Word (.docx), and PDF documents.`);
    }

    onProgress({ status: `Uploading ${file.name} to Python scanner...`, progress: 10 });

    const formData = new FormData();
    formData.append('file', file, file.name);
    const response = await fetch('/api/scan-file', { method: 'POST', body: formData });
    const payload = await response.json().catch(() => ({}));

    if (!response.ok) {
      throw new Error(payload.detail || `Scanner service returned HTTP ${response.status}.`);
    }

    onProgress({ status: 'Parsing document and generating chart draft...', progress: 75 });
    const parsedResult = this.normalizePythonResult(payload, file);

    onProgress({ status: 'Compiling extracted draft package...', progress: 90 });

    // Aggregate Full Scan Package
    const scanPackage = {
      id: `scan_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`,
      name: file.name,
      type: category,
      size: file.size,
      scannedAt: new Date().toISOString(),
      rawText: parsedResult.rawText,
      metadata: parsedResult.metadata,
      formattedHtml: parsedResult.formattedHtml,
      previewUrl: parsedResult.previewUrl,
      sheetsData: parsedResult.sheetsData,
      pages: parsedResult.pages,
      pdfBuffer: parsedResult.pdfBuffer,
      pdfDocReference: parsedResult.pdfDocReference,
      docxBuffer: parsedResult.docxBuffer,   // Raw ArrayBuffer for docx-preview
      graphDrafts: parsedResult.graphDrafts,
      status: 'Pending Review'
    };

    // Save automatically to Database Manager
    await this.dbManager.saveRecord(scanPackage);

    onProgress({ status: 'Scan complete!', progress: 100 });

    return scanPackage;
  }

  normalizePythonResult(payload, file) {
    const tables = payload.data && Array.isArray(payload.data.tables) ? payload.data.tables : [];
    const sheetsData = {};
    tables.forEach((table, index) => {
      const sheetName = table.sheet_name || `Table ${index + 1}`;
      sheetsData[sheetName] = {
        headers: table.headers || [],
        rows: table.rows || []
      };
    });

    const suggestion = payload.visualization_draft || {};
    const seriesConfig = suggestion.series_config || {};
    const graphDrafts = suggestion.suggested_chart_type ? [{
      title: `${suggestion.suggested_chart_type.toUpperCase()} chart draft`,
      source: file.name,
      primaryType: suggestion.suggested_chart_type,
      recommendation: suggestion.rationale || 'Draft visualization generated by the Python scanner.',
      chartData: {
        labels: (seriesConfig.data_preview || []).map(item => item.label),
        values: (seriesConfig.data_preview || []).map(item => item.value),
        xAxis: seriesConfig.x_axis,
        yAxis: seriesConfig.y_axis
      }
    }] : [];

    return {
      rawText: (payload.data && payload.data.raw_text_preview) || '',
      metadata: payload.scan_metadata || {},
      sheetsData,
      graphDrafts,
      fields: (payload.data && payload.data.fields) || [],
      tables
    };
  }
}

if (typeof window !== 'undefined') {
  window.ScannerOrchestrator = ScannerOrchestrator;
}
