-- Retired legacy schema reference.
-- This file formerly created and selected the pre-3NF `iris_db` database.
-- Do not import it. IRIS V4.5.0 connects to the separately provisioned `iris_db_3nf` schema.
-- Apply only reviewed, explicit migrations that target `iris_db_3nf`.
